<?php echo $this->doctype(). "\n";?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Sistema de Gestão de Cemitérios -  EmpSoft Informática</title>
  <link href="/images/favicon.ico" type="image/x-icon" rel="shortcut icon"/>
  <?php echo $this->headMeta()."\n"; ?>
  <?php echo $this->headTitle()."\n"; ?>
  <?php echo $this->headLink() . "\n"; ?>
  <?php echo $this->headScript() . "\n"; ?>
  <?php echo $this->headStyle() . "\n"; ?>  
</head>	
<body>
   <div id="header">
     <p>ERP EMPSOFT-CMS - Sistema de Gestão de Cemitério 3.0</p>
   <div>
   <div id="btn-1"></div>   
</body>
</html>